postgresql:
  master:
    labels:
      branch: $BRANCH_NAME
      team: platform
      usage: utests
    podLabels:
      branch: $BRANCH_NAME
      resource: pod
      team: platform
      usage: utests
tags:
  postgresql: true
